version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: transaction_service
    volumes:
      - db:/var/lib/postgresql/data

  transaction-service:
    build:
      context: ./
    restart: always
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
    ports:
      - 8080:8080

volumes:
  db:
